#!/usr/bin/env python3
"""Generate a command-line test runner for the CleanMacTests target.

Scans CleanMacTests/*.swift for XCTestCase subclasses and their `func testX()`
methods, then emits Swift that instantiates each case, runs setUp / the test /
tearDown, and reports the results. This lets the suite actually execute on a
machine that has the Command Line Tools but no XCTest.framework.
"""
import os
import re
import sys

CLASS_RE = re.compile(r"^(?:final\s+)?class\s+(\w+)\s*:\s*XCTestCase\b")
TEST_RE = re.compile(
    r"^\s*func\s+(test\w*)\s*\(\s*\)\s*(async\b)?\s*(throws\b)?\s*\{"
)


def scan(test_dir):
    suites = []  # [(class_name, [(method, is_async, is_throws)])]
    for name in sorted(os.listdir(test_dir)):
        if not name.endswith(".swift"):
            continue
        path = os.path.join(test_dir, name)
        current = None
        methods = []
        with open(path, encoding="utf-8") as handle:
            for line in handle:
                cls = CLASS_RE.match(line)
                if cls:
                    if current:
                        suites.append((current, methods))
                    current = cls.group(1)
                    methods = []
                    continue
                test = TEST_RE.match(line)
                if test and current:
                    methods.append(
                        (test.group(1), bool(test.group(2)), bool(test.group(3)))
                    )
        if current:
            suites.append((current, methods))
    return suites


def invocation(cls, method, is_async, is_throws):
    prefix = "try " if is_throws else ""
    mid = "await " if is_async else ""
    return "%s%s(c as! %s).%s()" % (prefix, mid, cls, method)


def main():
    if len(sys.argv) != 3:
        print("usage: genrunner.py <CleanMacTests dir> <output.swift>", file=sys.stderr)
        return 2
    suites = scan(sys.argv[1])
    out = []
    out.append("// GENERATED by .verify/genrunner.py — do not edit.")
    out.append("import Foundation")
    out.append("import XCTest")
    out.append("")
    out.append("struct XCTGeneratedTest {")
    out.append("    let suite: String")
    out.append("    let name: String")
    out.append("    let make: () -> XCTestCase")
    out.append("    let body: (XCTestCase) async throws -> Void")
    out.append("}")
    out.append("")
    out.append("let XCTGeneratedTests: [XCTGeneratedTest] = [")
    total = 0
    for cls, methods in suites:
        for method, is_async, is_throws in methods:
            out.append(
                '    XCTGeneratedTest(suite: "%s", name: "%s", make: { %s() }, '
                "body: { c in %s }),"
                % (cls, method, cls, invocation(cls, method, is_async, is_throws))
            )
            total += 1
    out.append("]")
    out.append("")
    out.append("func XCTRunGeneratedTests() async -> Int32 {")
    out.append("    var passed = 0, failed = 0, skipped = 0")
    out.append("    var log: [String] = []")
    out.append("    var lastSuite = \"\"")
    out.append("    for test in XCTGeneratedTests {")
    out.append("        if test.suite != lastSuite {")
    out.append('            print("\\n== \\(test.suite) ==")')
    out.append("            lastSuite = test.suite")
    out.append("        }")
    out.append("        let instance = test.make()")
    out.append("        XCTFailureRecorder.shared.reset()")
    out.append("        var failures: [String] = []")
    out.append("        var skipReason: String?")
    out.append("        var crashed: String?")
    out.append("        do {")
    out.append("            try instance.setUpWithError()")
    out.append("            instance.setUp()")
    out.append("            try await test.body(instance)")
    out.append("        } catch let error as XCTSkip {")
    out.append("            skipReason = error.reason")
    out.append("        } catch {")
    out.append('            crashed = "\\(error)"')
    out.append("        }")
    out.append("        failures = XCTFailureRecorder.shared.failures")
    out.append("        if let reason = crashed {")
    out.append('            failures.append("threw: \\(reason)")')
    out.append("        }")
    out.append("        do {")
    out.append("            try instance.tearDownWithError()")
    out.append("        } catch {")
    out.append('            failures.append("tearDownWithError threw: \\(error)")')
    out.append("        }")
    out.append("        instance.tearDown()")
    out.append("        if let reason = skipReason, failures.isEmpty {")
    out.append("            skipped += 1")
    out.append('            print("  SKIP  \\(test.name) — \\(reason)")')
    out.append("        } else if failures.isEmpty {")
    out.append("            passed += 1")
    out.append('            print("  pass  \\(test.name)")')
    out.append("        } else {")
    out.append("            failed += 1")
    out.append('            print("  FAIL  \\(test.suite).\\(test.name)")')
    out.append("            for failure in failures {")
    out.append('                print("        \\(failure)")')
    out.append('                log.append("\\(test.suite).\\(test.name): \\(failure)")')
    out.append("            }")
    out.append("        }")
    out.append("    }")
    out.append('    print("\\n----------------------------------------")')
    out.append("    if failed > 0 {")
    out.append('        print("FAILURES (\\(failed)):")')
    out.append("        for entry in log { print(\"  \\(entry)\") }")
    out.append("    }")
    out.append('    print("\\n\\(passed) passed, \\(failed) failed, \\(skipped) skipped '
               '(\\(passed + failed + skipped) total)")')
    out.append("    return failed == 0 ? 0 : 1")
    out.append("}")
    out.append("")
    with open(sys.argv[2], "w", encoding="utf-8") as handle:
        handle.write("\n".join(out) + "\n")
    print("generated %d test(s) across %d suite(s)" % (total, len(suites)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
