//
//  TestResources.swift
//  CleanMacTests
//
//  Locates the real rule packs from the source tree so tests exercise the
//  same YAML the app ships, instead of a hand-written copy that can drift.
//

import Foundation
@testable import CleanMac

enum TestResources {

    /// `<repo>` — the checkout root, holding `project.yml`.
    static var repositoryRoot: String {
        // #filePath -> <repo>/CleanMacTests/TestResources.swift
        let dir = (#filePath as NSString).deletingLastPathComponent   // <repo>/CleanMacTests
        return (dir as NSString).deletingLastPathComponent            // <repo>
    }

    /// `.../CleanMac` — the app target's source root.
    static var appSourceDirectory: String {
        (repositoryRoot as NSString).appendingPathComponent("CleanMac")
    }

    /// `.../CleanMac/Resources` — the folder XcodeGen copies as a folder
    /// reference into the app bundle.
    static var resourcesDirectory: String {
        (appSourceDirectory as NSString).appendingPathComponent("Resources")
    }

    static var rulesDirectory: String {
        (resourcesDirectory as NSString).appendingPathComponent("Rules")
    }

    /// The string catalog generated by `.verify/genstrings.py --write`.
    static var catalogPath: String {
        (resourcesDirectory as NSString).appendingPathComponent("Localizable.xcstrings")
    }

    /// True when the source tree is reachable. Tests that read files off disk
    /// skip rather than fail when it is not (some CI checkouts ship only the
    /// compiled products).
    static var isSourceAvailable: Bool {
        FileManager.default.fileExists(atPath: appSourceDirectory)
    }

    /// A bundle whose resource path is the source `Resources` folder, so
    /// `RuleLoader.loadBundled(named:)` resolves `Rules/<name>.yaml`.
    static var bundle: Bundle {
        Bundle(url: URL(fileURLWithPath: resourcesDirectory, isDirectory: true)) ?? .main
    }

    static var ruleLoader: RuleLoader {
        RuleLoader(bundle: bundle, fileSystem: LiveFileSystem())
    }

    static func yaml(named name: String) throws -> String {
        let path = (rulesDirectory as NSString).appendingPathComponent("\(name).yaml")
        return try String(contentsOfFile: path, encoding: .utf8)
    }

    /// True when the rule packs are reachable (they are absent in some
    /// CI checkouts). Tests that depend on them skip rather than fail.
    static var isAvailable: Bool {
        FileManager.default.fileExists(atPath: rulesDirectory)
    }
}
